version: '3.5'
services:
  postgres:
    container_name: learnify
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: learnifydbpassword
      POSTGRES_DB: learnify
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - '5432:5432'

volumes:
  postgres-db:
    driver: local
